/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.VendaDao;
import Model.ItensVenda;
import Model.Venda;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class FrmConsultarVendas extends javax.swing.JInternalFrame {

    private DefaultTableModel tableModelVenda;
    private DefaultTableModel tableModelItensVenda;
    private List<Venda> listaVenda;
    private List<ItensVenda> listaItensVenda;
    private ListSelectionModel listModelVenda;

    /**
     * Creates new form FrmConsultarVendas
     */
    public FrmConsultarVendas() {
        initComponents();
        defineModelo();
    }

    private void defineModelo() {
        tableModelVenda = (DefaultTableModel) jTableClienteVenda.getModel();
        tableModelItensVenda = (DefaultTableModel) jTableProdutoVenda.getModel();
        listModelVenda = jTableClienteVenda.getSelectionModel();
        listModelVenda.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    mostraDetalheVenda();
                }
            }
        });
        try {
            jTableProdutoVenda.getColumnModel().getColumn(0).setPreferredWidth(400);
            jTableClienteVenda.getColumnModel().getColumn(1).setPreferredWidth(500);
        } catch (Exception ex) {
            Logger.getLogger(FrmRegistrarVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void atualizaTabela() {
        VendaDao vendaDao = new VendaDao();
        java.sql.Date dataInicial = new java.sql.Date(((java.util.Date) jFormattedTextDataInicial.getValue()).getTime());
        java.sql.Date dataFinal = new java.sql.Date(((java.util.Date) jFormattedTextDataFinal.getValue()).getTime());
        listaVenda = vendaDao.consultaVendaPeriodo(dataInicial, dataFinal);

        int numeroLinhas = jTableClienteVenda.getRowCount();
        for (int i = 0; i < numeroLinhas; i++) {
            tableModelVenda.removeRow(0);
        }
        for (int i = 0; i < listaVenda.size(); i++) {
            tableModelVenda.insertRow(i, new Object[]{listaVenda.get(i).getId(),
                        listaVenda.get(i).getCliente().getNome(),
                        listaVenda.get(i).getDataVenda()
                    });
        }
    }
private void mostraDetalheVenda() {
        if (jTableClienteVenda.getSelectedRow() != -1) {
            listaItensVenda = listaVenda.get(jTableClienteVenda.getSelectedRow()).getItensVenda();
            removeItensVenda();
            for (int i = 0; i < listaItensVenda.size(); i++) {
                tableModelItensVenda.insertRow(i, new Object[]{listaItensVenda.get(i).getProduto().getNome(),
                            listaItensVenda.get(i).getQtde(),
                            listaItensVenda.get(i).getProduto().getValor(),
                            listaItensVenda.get(i).getProduto().getValor() * listaItensVenda.get(i).getQtde()
                        });
            }
        } else {
            removeItensVenda();
        }
    }
private void removeItensVenda(){
        int numeroLinhas = jTableProdutoVenda.getRowCount();
        for (int i = 0; i < numeroLinhas; i++) {
            tableModelItensVenda.removeRow(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClienteVenda = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextDataInicial = new javax.swing.JFormattedTextField();
        jFormattedTextDataFinal = new javax.swing.JFormattedTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProdutoVenda = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Java GUI Swuing - TADS 2022/3!!!!");
        setPreferredSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultar Vendas");
        jPanel1.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Data Incial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setText("DataFinal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        jTableClienteVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Data Venda"
            }
        ));
        jTableClienteVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableClienteVenda);
        if (jTableClienteVenda.getColumnModel().getColumnCount() > 0) {
            jTableClienteVenda.getColumnModel().getColumn(0).setMinWidth(1);
            jTableClienteVenda.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 664;
        gridBagConstraints.ipady = 111;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 5);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jLabel4.setText("Item Venda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 0, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        jFormattedTextDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jFormattedTextDataInicial, gridBagConstraints);

        jFormattedTextDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jFormattedTextDataFinal, gridBagConstraints);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jButtonPesquisar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel2, gridBagConstraints);

        jTableProdutoVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Qtde", "Vlr. Unit.", "Vlr. Total"
            }
        ));
        jTableProdutoVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableProdutoVenda);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
if (jFormattedTextDataInicial.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data inicial!", "Erro", JOptionPane.ERROR_MESSAGE);
            jFormattedTextDataInicial.requestFocus();
        } else if (jFormattedTextDataFinal.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data final!", "Erro", JOptionPane.ERROR_MESSAGE);
            jFormattedTextDataInicial.requestFocus();
        } else {
            atualizaTabela();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextDataFinal;
    private javax.swing.JFormattedTextField jFormattedTextDataInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableClienteVenda;
    private javax.swing.JTable jTableProdutoVenda;
    // End of variables declaration//GEN-END:variables
}
